//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЗапКомЧасть.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int idCountry { get; set; }
        public string Name { get; set; }
        public string CarBrands { get; set; }
        public string CooperationOnDetails { get; set; }
        public string BusinessTripCooperation { get; set; }
        public Nullable<int> id_ChiefWorkshop { get; set; }
        public Nullable<int> id_ChiefDepartmant { get; set; }
    
        public virtual ChiefDepartmant ChiefDepartmant { get; set; }
        public virtual ChiefWorkshop ChiefWorkshop { get; set; }

        public string Brands
        {
            get
            {
                string info = CarBrands;
                string[] avtoName = info.Split(Convert.ToChar(","));
                info = "";
                for (int i = 0; i < avtoName.Length; i++)
                {
                    info += avtoName[i];
                    if (i != avtoName.Length - 1)
                    {
                        info += "\n";
                    }
                }
                return info;

            }
        }
    }
}
