//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЗапКомЧасть.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departmant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departmant()
        {
            this.OfficeEmployees = new HashSet<OfficeEmployee>();
            this.OfficeSecondments = new HashSet<OfficeSecondment>();
        }
    
        public int idDepartmant { get; set; }
        public string Name { get; set; }
        public int id_Chief { get; set; }
        public string Responsibilities { get; set; }
    
        public virtual ChiefDepartmant ChiefDepartmant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeEmployee> OfficeEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeSecondment> OfficeSecondments { get; set; }


        public string Respons
        {
            get
            {
                string info = Responsibilities;
                string[] responsTxt = info.Split(Convert.ToChar(","));
                info = "";
                for (int i = 0; i < responsTxt.Length; i++)
                {
                    info += responsTxt[i];
                    if (i != responsTxt.Length - 1)
                    {
                        info += "\n";
                    }
                }
                return info;

            }
        }
    }
}
