//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЗапКомЧасть.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int idDetails { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int CountInWarehouse { get; set; }
        public int id_Category { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
