//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЗапКомЧасть.bd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductionEntities : DbContext
    {
        public ProductionEntities()
            : base("name=ProductionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ChiefDepartmant> ChiefDepartmants { get; set; }
        public virtual DbSet<ChiefWorkshop> ChiefWorkshops { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Departmant> Departmants { get; set; }
        public virtual DbSet<Detail> Details { get; set; }
        public virtual DbSet<OfficeEmployee> OfficeEmployees { get; set; }
        public virtual DbSet<OfficeSecondment> OfficeSecondments { get; set; }
        public virtual DbSet<ProductionEmployee> ProductionEmployees { get; set; }
        public virtual DbSet<ProductionSecondment> ProductionSecondments { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Workshop> Workshops { get; set; }
    }
}
