//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЗапКомЧасть.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OfficeEmployee()
        {
            this.OfficeSecondments = new HashSet<OfficeSecondment>();
        }
    
        public int idOfficeEmployee { get; set; }
        public string Name { get; set; }
        public int id_Chief { get; set; }
        public int id_Departmant { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual ChiefDepartmant ChiefDepartmant { get; set; }
        public virtual Departmant Departmant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeSecondment> OfficeSecondments { get; set; }
    }
}
