//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЗапКомЧасть.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workshop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workshop()
        {
            this.ProductionEmployees = new HashSet<ProductionEmployee>();
            this.ProductionSecondments = new HashSet<ProductionSecondment>();
        }
    
        public int idWorkshop { get; set; }
        public string Name { get; set; }
        public int id_ChiefWorkshop { get; set; }
        public string Responsibilities { get; set; }
    
        public virtual ChiefWorkshop ChiefWorkshop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionEmployee> ProductionEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionSecondment> ProductionSecondments { get; set; }
    }
}
